function __host(op, argsArr) {
  var raw = __g_hostOp(op, JSON.stringify(argsArr || []));
  var r = (typeof raw === 'string') ? JSON.parse(raw) : raw;
  if (!r.ok) throw new Error(r.error || op);
  if (r.t === 'u' || r.v === undefined) return null;
  return r.v;
}
var __goauld = {
  sendJson: __g_sendJson,
  sendJsonData: __g_sendJsonData,
  engineName: function() { return 'symbiote'; },
  findExport: function(mod, name) {
    if (name === undefined) { name = mod; mod = ''; }
    return __host('findExport', [mod == null ? '' : String(mod), String(name)]);
  },
  findBase: function(name) { return __host('findBase', [name]); },
  readUtf8: function(addr) { return __host('readUtf8', [addr]); },
  processInfoJson: function() { return __host('processInfoJson', []); },
  enumerateModulesJson: function() { return __host('enumerateModulesJson', []); },
  findModuleByNameJson: function(name) { return __host('findModuleByNameJson', [name]); },
  findModuleByAddressJson: function(addr) { return __host('findModuleByAddressJson', [addr]); },
  enumerateRangesJson: function(prot, coalesce) { return __host('enumerateRangesJson', [prot, coalesce]); },
  findRangeByAddressJson: function(addr) { return __host('findRangeByAddressJson', [addr]); },
  enumerateThreadsJson: function() { return __host('enumerateThreadsJson', []); },
  threadSleep: function(secs) { return __host('threadSleep', [secs]); },
  threadBacktraceJson: function(accurate, max) { return __host('threadBacktraceJson', [accurate, max]); },
  memoryAlloc: function(size) { return __host('memoryAlloc', [size]); },
  memoryAllocAnon: function(size) { return __host('memoryAllocAnon', [size]); },
  memoryAllocUtf8: function(s) { return __host('memoryAllocUtf8', [s]); },
  memoryCopy: function(dst, src, n) { return __host('memoryCopy', [dst, src, n]); },
  memoryDup: function(addr, size) { return __host('memoryDup', [addr, size]); },
  memoryProtect: function(addr, size, prot) { return __host('memoryProtect', [addr, size, prot]); },
  memoryQueryProtection: function(addr) { return __host('memoryQueryProtection', [addr]); },
  memoryWriteBytes: function(addr, bytes) { return __host('memoryWriteBytes', [addr, bytes]); },
  memoryScanSyncJson: function(addr, size, pattern) { return __host('memoryScanSyncJson', [addr, size, pattern]); },
  clearIcache: function(addr, len) { return __host('clearIcache', [addr, len]); },
  moduleLoadJson: function(path) { return __host('moduleLoadJson', [path]); },
  enumerateExportsJson: function(name) { return __host('enumerateExportsJson', [name]); },
  enumerateImportsJson: function(name) { return __host('enumerateImportsJson', [name]); },
  enumerateSymbolsJson: function(name) { return __host('enumerateSymbolsJson', [name]); },
  enumerateSectionsJson: function(name) { return __host('enumerateSectionsJson', [name]); },
  enumerateDependenciesJson: function(name) { return __host('enumerateDependenciesJson', [name]); },
  attach: function(addr, leave, replace) { return __host('attach', [addr, leave, replace]); },
  detach: function(id) { return __host('detach', [id]); },
  detachAll: function() { return __host('detachAll', []); },
  flush: function() { return __host('flush', []); },
  replacePtr: function(addr, repl) { return __host('replacePtr', [addr, repl]); },
  call0: function(addr) { return __host('call0', [addr]); },
  call1: function(addr, a0) { return __host('call1', [addr, a0]); },
  call1Detached: function(addr, a0) { return __host('call1Detached', [addr, a0]); },
  evalAsync: function(source) { return __host('evalAsync', [source]); },
  scheduleTimer: function(delay, repeating) { return __host('scheduleTimer', [delay, repeating]); },
  cancelTimer: function(id) { return __host('cancelTimer', [id]); },
  runGc: function() { return __host('runGc', []); },
  consoleLog: function(level, message) { return __host('consoleLog', [level, message]); },
  arm64WriterNew: function(codeAddress, pc) { return __host('arm64WriterNew', [codeAddress, pc]); },
  arm64WriterOp: function(id, op, args) { return __host('arm64WriterOp', [id, op, args]); },
  arm64RelocatorNew: function(input, writerId) { return __host('arm64RelocatorNew', [input, writerId]); },
  arm64RelocatorOp: function(id, writerId, op, args) { return __host('arm64RelocatorOp', [id, writerId, op, args]); },
  arm64RelocatorSetSource: function(id, base, bytes) { return __host('arm64RelocatorSetSource', [id, base, bytes]); },
  cloakAddThread: function(id) { return __host('cloakAddThread', [id]); },
  cloakRemoveThread: function(id) { return __host('cloakRemoveThread', [id]); },
  cloakHasCurrentThread: function() { return __host('cloakHasCurrentThread', []); },
  cloakHasThread: function(id) { return __host('cloakHasThread', [id]); },
  cloakAddRange: function(base, size) { return __host('cloakAddRange', [base, size]); },
  cloakRemoveRange: function(base, size) { return __host('cloakRemoveRange', [base, size]); },
  cloakHasRangeContaining: function(addr) { return __host('cloakHasRangeContaining', [addr]); },
  cloakClipRangeJson: function(base, size) { return __host('cloakClipRangeJson', [base, size]); },
  cloakAddFd: function(fd) { return __host('cloakAddFd', [fd]); },
  cloakRemoveFd: function(fd) { return __host('cloakRemoveFd', [fd]); },
  cloakHasFd: function(fd) { return __host('cloakHasFd', [fd]); },
  wallClockSample: function() { return __host('wallClockSample', []); },
  cycleSample: function() { return __host('cycleSample', []); },
  userTimeSample: function(tid) { return __host('userTimeSample', [tid]); },
  mamEnableJson: function(rangesJson) { return __host('mamEnableJson', [rangesJson]); },
  mamDisable: function() { return __host('mamDisable', []); },
  startThreadObserver: function() { return __host('startThreadObserver', []); },
  stopThreadObserver: function() { return __host('stopThreadObserver', []); },
  setExceptionHandler: function(enabled) { return __host('setExceptionHandler', [enabled]); },
  exceptionProbeJson: function() { return __host('exceptionProbeJson', []); },
  scheduleOnThread: function(tid, token) { return __host('scheduleOnThread', [tid, token]); },
  spawnSleepThread: function(name, ms) { return __host('spawnSleepThread', [name, ms]); },
  javaEnsureVm: function() { return __host('javaEnsureVm', []); },
  javaIsMainThread: function() { return __host('javaIsMainThread', []); },
  javaAndroidVersion: function() { return __host('javaAndroidVersion', []); },
  javaNextMainToken: function() { return __host('javaNextMainToken', []); },
  javaScheduleMain: function(token) { return __host('javaScheduleMain', [token]); },
  javaEnumerateClassesJson: function() { return __host('javaEnumerateClassesJson', []); },
  javaEnumerateLoadersJson: function() { return __host('javaEnumerateLoadersJson', []); },
  javaClassMethodsJson: function(className) { return __host('javaClassMethodsJson', [className]); },
  javaClassFieldsJson: function(className) { return __host('javaClassFieldsJson', [className]); },
  javaReadStaticFieldJson: function(className, field) { return __host('javaReadStaticFieldJson', [className, field]); },
  javaDumpStorageJson: function() { return __host('javaDumpStorageJson', []); },
  javaHook: function(className, method, sig) { return __host('javaHook', [className, method, sig]); },
  javaCallOriginal: function(key, x) { return __host('javaCallOriginal', [key, x]); },
  androidToast: function(msg) { return __host('androidToast', [msg]); },
  stopAndroidApiTrace: function() { return __host('stopAndroidApiTrace', []); },
  traceAndroidApi: function(filter, maxEvents) {
    return __host('traceAndroidApi', [filter, maxEvents == null ? 0 : maxEvents]);
  },
};
